---
version: '3'
services:
  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    networks:
      - unifi_ntwk
    environment:
      - TZ=America/New_York
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped


  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    networks:
      - unifi_ntwk
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_USER=unifi
      - MONGO_PASS=ciscoisaweakpassword123
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - ./unifi-ntwk-app:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - unifi-db

networks:
  unifi_ntwk:
    driver: bridge
